# Generated by Django 4.0.4 on 2022-05-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_property_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, default='Sangotedo, Lagos', max_length=250),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=100000000),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Rent', 'rent'), ('For Sale', 'forSale'), ('Shortlet', 'Shortlet'), ('Land', 'land')], default='forSale', max_length=20),
        ),
    ]
