# Generated by Django 4.0.4 on 2022-05-11 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_property_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_space',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='toilet_count',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PhotoBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.property')),
            ],
        ),
    ]
