# Generated by Django 4.0.4 on 2022-05-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_property_bathroom_count_property_bedroom_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='No 23, Alagbado, Lagos', max_length=250),
        ),
    ]
