# Generated by Django 4.0.4 on 2022-07-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_property_purpose_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('shortlet', 'Shortlet'), ('land', 'Land')], default='forSale', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('flat', 'Flat'), ('land', 'Land'), ('house', 'House'), ('commercial', 'Commercial')], default='flat', max_length=20),
        ),
    ]
