# Generated by Django 4.0.4 on 2022-07-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_property_purpose_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cover_photo',
            field=models.ImageField(default='/download.jpg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='PhotoBook',
        ),
    ]
