# Generated by Django 4.0.4 on 2022-08-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_photobook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoBook',
            new_name='PropertyImage',
        ),
    ]
