# Generated by Django 4.0.4 on 2022-08-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_photobook_propertyimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyImage',
            new_name='PhotoBook',
        ),
    ]
